# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest:80, host:7999, auto_correct: true
  #config.vm.synced_folder ".", "/var/www/html"
  config.vm.network :private_network, ip: "192.168.0.1"  
config.vm.provider "virtualbox" do |vb|
  vb.name = "Nging_Webserver"
  vb.cpus = "2"
  vb.memory = "1024"
end
config.vm.provision "shell", path: "shells.sh" 
end